In [ ]:
import pandas as pd
import mysql.connector as sqltor
mycon=sqltor.connect(host='localhost',user='root',password='root',database= “d1” )
print (*****)
print (‘Select’)
print (‘1  if you want to Insert a record’)
print (‘2  if you want to delete a record’)
print (‘3  if you want to update   availability  in a record ’)
print (‘4  if you want to display no:of  books from  each genre ’)
print (‘5  if you want to  compare  availability  of  all books’)
print (*****)
mycursor=mycon.cursor()
df1=pd.read_sql(‘select*from  books;',mycon)
print(df1)
s=int(input('Enter your choice: '))
if s==1:
    qry='insert into books values(%s,%s,%s,%s,%s);'
    val=eval(input('Enter values: '))
    mycursor.execute(qry,val)
    mycon.commit()
    print('Record inserted successfully')
elif s==2:
    a=eval(input('Enter  book code  which is to be deleted 
        (in quotes) '))
    qry2='delete from  books where  book_code=%s;'
    val=(a,)
    mycursor.execute(qry2,val)
    mycon.commit()
    print('Record deleted successfully')
elif s==3:
    a=input(' Enter book_code of  the book')
    b=eval(input(‘Enter updated availability’))
    qry3='update   books set availability=%s where  
      book_code=%s;'
    val=(b,a)
    mycursor.execute(qry3,val)
    mycon.commit()
    print('Record updated successfully')
elif s==4:
    import matplotlib.pyplot as plt
    df=pd.read_sql('select count(*), genre from
    books  group by genre;',mycon)
    df1=pd.read_sql('select distinct  genre from
    books order by genre;',mycon)
    plt.bar(df[‘genre’],df['count(*)'],width=3,color='c')
    plt.title('Number of  each genre')
    plt.xlabel(‘type of genre’)
    plt.ylabel('Number of books')
    plt.xticks(df1['genre])
    plt.show()
elif s==5:
    import matplotlib.pyplot as plt
    qry5='select count(availability),availability from books     
       group by availability;'
    df3=pd.read_sql(qry5,mycon)
    plt.bar(df3['gender'],df3['count(gender)'],color=['g','r'])
    plt.ylabel('Number of  books available')
    plt.ylim(0,11)
    plt.show()
else:
    print('Invalid choice')
    print('Thank you')